import Head from "next/head";

import NavBar from "@/components/Navigation/Navbar";
import HomeHero from "@/components/HomeHero";
import AboutUs from "@/components/AboutMe";
import SkillsShowcase from "@/components/SkillsShowcase";
import Projects from "@/components/Projects";
import ContactMe from "@/components/ContactMe";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kevin Tanzyl | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="google-site-verification"
          content="JFiYK7-30EetcsS8Axti9pL0yksNaxNUBiwZpFh03Bc"
        />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <NavBar />
      <main>
        <HomeHero />
        <AboutUs />
        <SkillsShowcase />
        <Projects />
        <ContactMe />
        <Footer />
      </main>
    </>
  );
}
